// === AUDIT STATUS ===
// internal:    { status: not started, auditors: [], commit: }
// external_1:  { status: not started, auditors: [], commit: }
// external_2:  { status: not started, auditors: [], commit: }
// =====================

#pragma once

#include "barretenberg/numeric/uint256/uint256.hpp"

// Straight-line addition chains for Fermat inversion (`x^(p-2)`) on the two BN254
// primes. Each chain is derived from Michael McLoughlin's `addchain` tool
// (github.com/mmcloughlin/addchain) with default heuristics and is verified
// symbolically against a reference binary exponentiation in the companion test
// `bn254_fermat_addchain.test.cpp`.
//
// Op counts (barretenberg Montgomery kernels):
//   - Fr (`r-2`): 250 sqr + 55 mul = 305 ops.
//   - Fq (`q-2`): 247 sqr + 56 mul = 303 ops.
// Naive binary exponent (for a 254-bit exponent of Hamming weight 127) costs
// 253 sqr + 126 mul = 379 ops, so each specialized chain saves ~70 kernel
// calls per inversion relative to `pow(modulus_minus_two)`.
//
// The chains are header-only and `constexpr`-safe. They rely only on
// `field::sqr`, `field::self_sqr`, `operator*` and `operator*=`, so they work
// uniformly across native (`__int128`), WASM int29 and WASM FMA backends.

namespace bb::detail::bn254_fermat_addchain {

// BN254 scalar field modulus: r = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001.
inline constexpr numeric::uint256_t bn254_fr_modulus{
    0x43E1F593F0000001UL, 0x2833E84879B97091UL, 0xB85045B68181585DUL, 0x30644E72E131A029UL
};

// BN254 base field modulus: q = 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47.
inline constexpr numeric::uint256_t bn254_fq_modulus{
    0x3C208C16D87CFD47UL, 0x97816A916871CA8DUL, 0xB85045B68181585DUL, 0x30644E72E131A029UL
};

template <class Modulus> inline constexpr bool params_modulus_equals(const numeric::uint256_t& target)
{
    return Modulus::modulus_uint256 == target;
}

// Addition chain for Fr exponent r-2, derived from `addchain search r-2`.
// Produces 305 total Montgomery operations (250 sqr + 55 mul). The chain is
// straight-line: no branches, all temporaries live on the stack.
template <class Field> constexpr Field invert_bn254_fr(const Field& input) noexcept
{
    const Field x = input;
    Field z{};
    Field t0{};
    Field t1{};
    Field t2{};
    Field t3{};
    Field t4{};
    Field t5{};
    Field t6{};
    Field t7{};

    t0 = x.sqr();
    t4 = x * t0;
    t2 = t0 * t4;
    z = t0 * t2;
    t3 = t0 * z;
    t1 = t0 * t3;
    t5 = t0 * t1;
    t6 = t0 * t5;
    t7 = t3 * t6;
    t0 = z * t7;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t4;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= x;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t3;
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t4;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= z;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t1;
    t7.self_sqr();
    t7 *= x;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t3;
    t7.self_sqr();
    t7 *= x;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t5;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t2;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t5;
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t4;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t2;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= x;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t1;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t5;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t2;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t4;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t2;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t4;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t1;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t2;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t2;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t4;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t0;
    t7.self_sqr();
    t7.self_sqr();
    t7 *= x;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7 *= t3;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t6 *= t7;
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t5 *= t6;
    t5.self_sqr();
    t5.self_sqr();
    t4 *= t5;
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4 *= t1;
    t4.self_sqr();
    t4 *= x;
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t3 *= t4;
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t2 *= t3;
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2 *= t0;
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2 *= t0;
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t1 *= t2;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1 *= x;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1 *= t0;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1 *= t0;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1 *= t0;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1 *= t0;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1 *= t0;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t0 *= t1;
    t0.self_sqr();
    t0.self_sqr();
    t0.self_sqr();
    z *= t0;

    return z;
}

// Addition chain for Fq exponent q-2, derived from `addchain search q-2`.
// Produces 303 total Montgomery operations (247 sqr + 56 mul).
template <class Field> constexpr Field invert_bn254_fq(const Field& input) noexcept
{
    const Field x = input;
    Field z{};
    Field t0{};
    Field t1{};
    Field t2{};
    Field t3{};
    Field t4{};
    Field t5{};
    Field t6{};
    Field t7{};
    Field t8{};
    Field t9{};
    Field t10{};
    Field t11{};
    Field t12{};
    Field t13{};
    Field t14{};
    Field t15{};
    Field t16{};
    Field t17{};
    Field t18{};
    Field t19{};
    Field t20{};
    Field t21{};

    t8 = x.sqr();
    t15 = x * t8;
    z = t8 * t15;
    t1 = x * z;
    t3 = t8 * t1;
    t9 = z * t3;
    t6 = z * t9;
    t19 = x * t6;
    t0 = x * t19;
    t20 = t15 * t0;
    t2 = z * t20;
    t17 = t9 * t19;
    t4 = t15 * t17;
    t14 = t3 * t4;
    t12 = t19 * t2;
    t16 = t6 * t12;
    t18 = t6 * t16;
    t3 *= t18;
    t5 = t1 * t3;
    t0 *= t5;
    t10 = t2 * t0;
    t7 = t17 * t0;
    t11 = t17 * t7;
    t13 = t1 * t11;
    t21 = t1 * t13;
    t2 = t8 * t21;
    t6 *= t21;
    t17 *= t21;
    t8 *= t17;
    t1 *= t17;
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21 *= t10;
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21 *= t1;
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t21.self_sqr();
    t20 *= t21;
    t20.self_sqr();
    t20.self_sqr();
    t20.self_sqr();
    t20.self_sqr();
    t20.self_sqr();
    t20.self_sqr();
    t20.self_sqr();
    t20.self_sqr();
    t20.self_sqr();
    t19 *= t20;
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19 *= t9;
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t19.self_sqr();
    t18 *= t19;
    t18.self_sqr();
    t18.self_sqr();
    t18.self_sqr();
    t18.self_sqr();
    t18.self_sqr();
    t18.self_sqr();
    t18.self_sqr();
    t18.self_sqr();
    t18.self_sqr();
    t17 *= t18;
    t17.self_sqr();
    t17.self_sqr();
    t17.self_sqr();
    t17.self_sqr();
    t17.self_sqr();
    t17.self_sqr();
    t17.self_sqr();
    t17.self_sqr();
    t16 *= t17;
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16 *= t3;
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16 *= t9;
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t16.self_sqr();
    t15 *= t16;
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t15.self_sqr();
    t14 *= t15;
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t14.self_sqr();
    t13 *= t14;
    t13.self_sqr();
    t13.self_sqr();
    t13.self_sqr();
    t13.self_sqr();
    t13.self_sqr();
    t13.self_sqr();
    t13.self_sqr();
    t13.self_sqr();
    t12 *= t13;
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t12.self_sqr();
    t11 *= t12;
    t11.self_sqr();
    t11.self_sqr();
    t11.self_sqr();
    t11.self_sqr();
    t11.self_sqr();
    t11.self_sqr();
    t11.self_sqr();
    t11.self_sqr();
    t11.self_sqr();
    t10 *= t11;
    t10.self_sqr();
    t10.self_sqr();
    t10.self_sqr();
    t10.self_sqr();
    t10.self_sqr();
    t9 *= t10;
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t9.self_sqr();
    t8 *= t9;
    t8.self_sqr();
    t8.self_sqr();
    t8.self_sqr();
    t8.self_sqr();
    t8.self_sqr();
    t8.self_sqr();
    t8.self_sqr();
    t8.self_sqr();
    t7 *= t8;
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t7.self_sqr();
    t6 *= t7;
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t6.self_sqr();
    t5 *= t6;
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t5.self_sqr();
    t4 *= t5;
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t4.self_sqr();
    t3 *= t4;
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t3.self_sqr();
    t2 *= t3;
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t2.self_sqr();
    t1 *= t2;
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t1.self_sqr();
    t0 *= t1;
    t0.self_sqr();
    t0.self_sqr();
    t0.self_sqr();
    t0.self_sqr();
    t0.self_sqr();
    t0.self_sqr();
    z *= t0;

    return z;
}

} // namespace bb::detail::bn254_fermat_addchain
